### ISSUE TITLE
Option to change App Connector names

### ISSUE THREAD

**Issue by CKroes97** [zscaler/zpacloud-ansible#45]
### Is your feature request related to a problem?

We are working on a pipeline to deploy VMs and want to be able to rename app connectors in line with our internal naming convention. Currently I only see an Ansible module for getting app connector data, but not an option to change any details about an app connector. Can this be added.

### Describe the solution you'd like

A module zpa_app_connector_controller that allows to give a new name for an existing app connector

### Describe alternatives you've considered

Alternative is putting an URI call in our playbooks but that is ugly and I'd prefer using a module.

### Additional context

Example rename that we would like to achieve \<app-connector-group-name\>-\<random number\> to \<app-connector-group\>-\<hostname\>

**Comment by CKroes97** [comment]
Just checking in to see whether this is a feature we can expect at some point or whether it has no priority

**Comment by willguibr** [comment]
Our team is currently evaluating and we will provide an answer in the next few days.

Zscaler DevRel.

**Comment by willguibr** [comment]
@CKroes97 
We have added a new resource `zpa_app_connector_controller` in the latest version v1.4.0 designed to allow for such operation.
However, be aware that the App Connector Controller APIs have limited functionalities in regards to which attributes are allowed to be configured.
The new resource only supports configuration of the following attributes: `name`, `description`, `enabled`. 
As for renaming an app connector, Ansible technically does not really have such capability. So, you will need to manage this operation based on the playbook logic itself. See an example below:
```yml
- name: App Connector Controller Management
  hosts: localhost
  tasks:
    - name: Retrieve App Connector Controller
      zscaler.zpacloud.zpa_app_connector_controller_info:
        name: 'new-docker-prov-key-zsdemo-zpa-1728492714762'
      register: app_connector_info

    - name: Rename App Connector Controller if it exists and has a different name
      when: app_connector_info.connectors[0].name is defined and app_connector_info.connectors[0].name != 'docker-prov-key-zsdemo-zpa-1728533383488'
      zscaler.zpacloud.zpa_app_connector_controller:
        id: "{{ app_connector_info.connectors[0].id }}"  # Use the ID for renaming
        name: 'docker-prov-key-zsdemo-zpa-1728533383488'  # Adjust this to match the actual current name
        description: "{{ app_connector_info.connectors[0].description | default('No description available') }}"
        enabled: "{{ app_connector_info.connectors[0].enabled }}"
      register: result
```
