### ISSUE TITLE
zscaler.zpacloud.zpa_ba_certificate not working

### ISSUE THREAD

**Issue by borgermeister** [zscaler/zpacloud-ansible#65]
Hi

How is this module supposed to be used? I've tried several different approaches but none of them works.

I have a playbook that creates a CSR and retrieves the certificate using the `community.crypto.acme_certificate` module. That is working just fine and I can use the certificate on HAProxy just to verify that the certificate is OK.

However when I try to upload the certificate using this module it fails.

In this example I first created the CSR in Zscaler Experience Center.

```yaml
- name: Onboard ZPA BA Certificate
  zscaler.zpacloud.zpa_ba_certificate:
    provider: "{{ zscaler_zpa }}"
    name: pra.borgermeister.cloud
    description: Remote Borgermeister Cloud
    cert_blob: "{{ lookup('file', 'pra.borgermeister.cloud-fullchain.crt') }}"
```

```yaml
fatal: [localhost]: FAILED! => 
    changed: false
    msg: |-
        Error creating certificate: {
          "status": 400,
          "code": "resource.duplicate",
          "message": "A resource with name/id pra.borgermeister.cloud already exists ",
          "url": "https://api.zsapi.net/zpa/mgmtconfig/v1/admin/customers/xxx/certificate",
          "params": [
            "pra.borgermeister.cloud"
          ]
        }
```

When I try to upload a certificate+key as a new resource I get this error:

```yaml
fatal: [localhost]: FAILED! => 
    changed: false
    msg: |-
        Error creating certificate: {
          "status": 400,
          "code": "cert.no.matching.cert.found",
          "message": "No matching certificate present for the given private key",
          "url": "https://api.zsapi.net/zpa/mgmtconfig/v1/admin/customers/xxx/certificate"
        }
```

Can you please highlight the steps needed to be done to get this working?
